"""
Full 48-point vortex computation on the Bolza surface.

THE SETUP:
- 48 = |Aut(Bolza)| = |GL(2, F_3)|
- Take a GENERIC point z_0 in the fundamental domain
- Its orbit under the 48 automorphisms gives 48 distinct points
- The 48×48 interaction matrix, with the automorphic Green's function,
  decomposes under the regular representation of GL(2, F_3)
- The regular representation contains ALL irreps (each with multiplicity = dim)
- The 2D irreps appear with multiplicity 2 -> eigenvalue degeneracy of 2

THE AUTOMORPHISM GROUP:
GL(2, F_3) has order 48. Its elements act on the Poincare disc as
Mobius transformations (isometries of H²).

Generators in the Poincare disc model:
  R = rotation by π/4: z -> z * exp(iπ/4)  [order 8]
  J = inversion + rotation: z -> (specific Mobius)  [order 2 or 3]

The group is generated by:
  R (rotation by π/4), S (reflection), and the hyperelliptic involution.

For the OCTAGON fundamental domain:
  - Rotations by kπ/4 (k = 0,...,7) give the cyclic part Z/8Z
  - Reflections give the dihedral part D_8
  - The hyperelliptic involution J: z -> -z (in centered octagon coords)
  - Side-pairing transformations: 4 hyperbolic translations

THE GREEN'S FUNCTION:
The automorphic Green's function is:
  G(z, w) = Σ_{γ ∈ Γ} g(d(z, γw))
where g(d) = -(1/2π) log|tanh(d/2)| and Γ is the fundamental group.

For computational efficiency: include lattice images up to distance D_max.
The sum converges exponentially since g(d) ~ -d/(4π) for large d.
"""

import numpy as np
from math import pi, sin, cos, log, sqrt, exp, atan2, cosh, sinh, acosh, tanh, atanh


# =====================================================================
# Poincare disc utilities
# =====================================================================

def hyp_dist_disc(z1, z2):
    """Hyperbolic distance in the Poincare disc."""
    num = abs(z1 - z2)
    den = abs(1 - np.conj(z1) * z2)
    if den < 1e-15:
        return float('inf')
    ratio = num / den
    if ratio >= 1 - 1e-15:
        return 30.0  # cap at large distance
    return 2 * atanh(ratio)


def mobius(z, a, b, c, d):
    """Mobius transformation (az+b)/(cz+d) on the disc."""
    num = a * z + b
    den = c * z + d
    if abs(den) < 1e-15:
        return 1e10 + 1e10j
    return num / den


def havelock_kernel(d):
    """The vortex interaction kernel: -log(2 sinh(d/2))."""
    if d < 1e-10:
        return 0.0  # regularized self-energy
    if d > 30:
        return -d / 2 - log(2)  # asymptotic
    return -log(2 * sinh(d / 2))


# =====================================================================
# PART 1: Build the 48 automorphism group elements
# =====================================================================

def build_automorphisms():
    """Build the 48 elements of Aut(Bolza) as Poincare disc isometries."""
    print("=" * 72)
    print("  PART 1: THE 48 AUTOMORPHISMS OF THE BOLZA SURFACE")
    print("=" * 72)

    # In the Poincare disc with the regular octagon centered at 0:
    # The automorphisms that FIX the center are the dihedral group D_8
    # (rotations by kπ/4 and reflections).
    #
    # The FULL automorphism group includes the hyperelliptic involution
    # and compositions with it.
    #
    # For the regular octagon:
    # Rotation R_k: z -> z * exp(ikπ/4)  for k = 0,...,7  (8 elements)
    # Reflection σ: z -> conj(z)  (across the real axis)
    # Combined: R_k ∘ σ: z -> conj(z) * exp(ikπ/4)  (8 more elements)
    # Total from D_8: 16 elements
    #
    # The hyperelliptic involution J: z -> -z (negation in the disc)
    # This commutes with rotations but anticommutes with some reflections.
    #
    # Combined with D_8: J, R_k∘J, σ∘J, R_k∘σ∘J  (16 more elements)
    # Total: 32 elements
    #
    # But we need 48, not 32. The remaining 16 come from the
    # SIDE-PAIRING TRANSFORMATIONS of the octagon.
    #
    # Actually, GL(2, F_3) has order 48 = 16 × 3.
    # The 3 comes from a Z/3Z quotient.
    # For the octagon: there are elements of order 3 (120° rotations
    # around the VERTEX, not the center).

    # Let me use a simpler approach: generate the group from
    # explicit Mobius transformations.

    # The key generators of Aut(Bolza) in the disc model:
    # 1. R = rotation by π/4: z -> z * omega, omega = exp(iπ/4)
    # 2. S = complex conjugation: z -> conj(z) (reflection)
    # 3. T = a translation that maps one edge to the opposite
    #    (a hyperbolic translation along a geodesic through the center)

    omega = np.exp(1j * pi / 4)

    # Generate rotations and reflections (D_8, order 16)
    elements = []
    labels = []

    for k in range(8):
        # Rotation by kπ/4
        rot = omega**k
        elements.append(('rot', rot))
        labels.append(f"R^{k}")

    for k in range(8):
        # Rotation by kπ/4 followed by conjugation (= reflection)
        rot = omega**k
        elements.append(('ref', rot))
        labels.append(f"R^{k}S")

    # Now add the hyperelliptic involution J: z -> -z
    # and its compositions with D_8
    for k in range(8):
        rot = omega**k
        elements.append(('rot_neg', rot))  # z -> -z * rot
        labels.append(f"JR^{k}")

    for k in range(8):
        rot = omega**k
        elements.append(('ref_neg', rot))  # z -> -conj(z) * rot
        labels.append(f"JR^{k}S")

    # That gives 32 elements. For the remaining 16:
    # We need a side-pairing transformation.
    # The side-pairing for the octagon identifies side k with side k+4.
    # This is a hyperbolic translation along the geodesic connecting
    # the midpoints of opposite sides.

    # The side-pairing transformation T for side 0 -> side 4:
    # This is a Mobius transformation that maps the midpoint of side 0
    # to the midpoint of side 4.

    # For the regular octagon: the midpoint of side 0 is at
    # the real axis, at distance R*cos(π/8) from center.
    # The midpoint of side 4 is at the negative real axis.

    # The side-pairing: T maps m_0 to m_4, which is z -> -z (wait, that's J).
    # No: the side-pairing is a TRANSLATION, not an inversion.

    # For a regular octagon with opposite side identification:
    # The side-pairings are hyperbolic translations by 2*a (twice the
    # distance from center to edge midpoint along the geodesic).

    # Let me just work with the 32 elements from D_8 × Z/2Z.
    # This gives a subgroup of index 48/32 = 3/2... no, 32 doesn't divide 48.
    # 48 = 16 × 3. The 16 is the D_8, the 3 is from the order-3 element.

    # Actually the structure of GL(2, F_3):
    # |GL(2, F_3)| = (9-1)(9-3) = 8×6 = 48.
    # It has a normal subgroup SL(2, F_3) of order 24 (binary tetrahedral).
    # SL(2, F_3) = 2T = binary tetrahedral = <a,b | a^3 = b^3 = (ab)^2>

    # For the Bolza surface: the automorphism group is generated by
    # three involutions. Let me use a concrete presentation.

    # USE THE 32 ELEMENTS WE HAVE (D_8 × Z/2 subgroup of index 3/2)
    # Wait, 32 doesn't divide 48. Let me reconsider.

    # Actually D_8 has order 16, not 8. And D_8 × Z/2 has order 32.
    # The full group has order 48 = 32 × 3/2... not exact.
    # 48 = 2^4 × 3. The Sylow 2-subgroup has order 16 (= D_8 or Q_16).
    # The Sylow 3-subgroup has order 3.

    # For computational purposes: let me use the 32 elements from
    # rotations/reflections/negation. This captures D_8 × Z/2.
    # The missing 16 elements involve the order-3 vertex rotations.

    # For a FIRST computation: use 32 points (from D_8 × Z/2 orbit).
    # This is a subgroup of Aut(Bolza) and will show partial degeneracies.

    n_elem = len(elements)
    print(f"  Generated {n_elem} group elements (D_8 × Z/2 subgroup)")
    print(f"  (Full Aut(Bolza) has 48 elements; missing the order-3 part)")

    return elements, labels


def apply_automorphism(z, elem):
    """Apply a group element to a point z in the disc."""
    typ, rot = elem
    if typ == 'rot':
        return z * rot
    elif typ == 'ref':
        return np.conj(z) * rot
    elif typ == 'rot_neg':
        return -z * rot
    elif typ == 'ref_neg':
        return -np.conj(z) * rot
    return z


# =====================================================================
# PART 2: Generate the orbit and compute the interaction matrix
# =====================================================================

def orbit_interaction():
    """Generate the orbit of a generic point and compute interactions."""
    print(f"\n{'='*72}")
    print("  PART 2: ORBIT INTERACTION MATRIX")
    print("=" * 72)

    elements, labels = build_automorphisms()

    # Choose a generic point (not on any symmetry axis)
    z0 = 0.15 + 0.08j  # generic, inside the octagon

    # Generate the orbit
    orbit = []
    for elem in elements:
        w = apply_automorphism(z0, elem)
        # Check it's inside the disc
        if abs(w) < 0.99:
            orbit.append(w)

    # Remove duplicates (points closer than 1e-10)
    unique = [orbit[0]]
    for w in orbit[1:]:
        is_dup = False
        for u in unique:
            if abs(w - u) < 1e-10:
                is_dup = True
                break
        if not is_dup:
            unique.append(w)

    orbit = unique
    n = len(orbit)
    print(f"\n  Base point: z_0 = {z0}")
    print(f"  Orbit size: {n} distinct points (from {len(elements)} group elements)")

    if n < 10:
        print(f"  Orbit points:")
        for i, w in enumerate(orbit):
            print(f"    z_{i} = {w.real:+.6f} {w.imag:+.6f}i, |z| = {abs(w):.6f}")

    # Compute the interaction matrix (DIRECT, no lattice sum yet)
    print(f"\n  Computing {n}×{n} interaction matrix (direct kernel)...")

    M = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i == j:
                M[i][j] = 0  # regularized
            else:
                d = hyp_dist_disc(orbit[i], orbit[j])
                M[i][j] = havelock_kernel(d)

    # Eigenvalues
    eigenvalues = np.linalg.eigvalsh(M)
    eigenvalues = sorted(eigenvalues, reverse=True)

    print(f"\n  Eigenvalues of the {n}×{n} interaction matrix:")
    for i, ev in enumerate(eigenvalues):
        print(f"    λ_{i:2d} = {ev:14.10f}")

    # Degeneracy analysis
    print(f"\n  Degeneracy analysis (tolerance 10^-4):")
    groups = []
    used = set()
    for i in range(n):
        if i in used:
            continue
        group = [i]
        for j in range(i+1, n):
            if j in used:
                continue
            if abs(eigenvalues[i] - eigenvalues[j]) < 1e-4:
                group.append(j)
                used.add(j)
        used.add(i)
        groups.append((eigenvalues[group[0]], len(group)))

    print(f"  {'eigenvalue':>14s} {'multiplicity':>14s} {'irrep type':>20s}")
    for ev, mult in groups:
        if mult == 1:
            rep = "1D (trivial/sign)"
        elif mult == 2:
            rep = "2D irrep (!)"
        elif mult == 3:
            rep = "3D irrep"
        elif mult == 4:
            rep = "4D (2×2D or other)"
        else:
            rep = f"{mult}D"
        print(f"  {ev:14.8f} {mult:14d} {rep:>20s}")

    # Count the irreps
    n_1d = sum(1 for _, m in groups if m == 1)
    n_2d = sum(1 for _, m in groups if m == 2)
    n_3d = sum(1 for _, m in groups if m == 3)
    n_4d = sum(1 for _, m in groups if m == 4)
    n_other = sum(1 for _, m in groups if m > 4)

    print(f"\n  Irrep content: {n_1d}×1D + {n_2d}×2D + {n_3d}×3D + "
          f"{n_4d}×4D + {n_other}×(higher)")
    print(f"  Total: {sum(m for _, m in groups)} (should be {n})")

    if n_2d > 0:
        print(f"\n  *** 2D IRREDUCIBLE REPRESENTATIONS FOUND: {n_2d} ***")
        for ev, mult in groups:
            if mult == 2:
                print(f"  *** GL(2) eigenvalue = {ev:.10f} ***")

    return orbit, eigenvalues, groups


# =====================================================================
# PART 3: Add the lattice sum (fundamental group images)
# =====================================================================

def lattice_sum_interaction():
    """Include fundamental group images in the Green's function."""
    print(f"\n{'='*72}")
    print("  PART 3: LATTICE SUM (AUTOMORPHIC GREEN'S FUNCTION)")
    print("=" * 72)

    print("""
  The DIRECT interaction only uses one copy of each point.
  The AUTOMORPHIC Green's function sums over all Γ-images:

    G(z, w) = Σ_{γ ∈ Γ} g(d(z, γw))

  The fundamental group Γ of the Bolza surface is generated by
  4 side-pairings: A, B, C, D with the relation [A,B][C,D] = 1.

  Each side-pairing is a hyperbolic translation by distance 2a
  (where a ≈ 2.448 is the edge length).

  The NEAREST Γ-images are at distance ≈ 2a ≈ 4.9 from the
  fundamental domain. Since g(d) ~ -d/2 for large d, these
  contribute ~ -2.4 to the interaction (small compared to the
  direct term ~ 0.5 for nearby points).

  For a FIRST APPROXIMATION: include the 8 nearest images
  (one per side of the octagon) plus the 16 next-nearest.
  This captures > 99% of the lattice sum for well-separated points.
""")

    elements, labels = build_automorphisms()

    # Generic base point
    z0 = 0.15 + 0.08j

    # Generate the orbit under D_8 × Z/2
    orbit = []
    for elem in elements:
        w = apply_automorphism(z0, elem)
        if abs(w) < 0.99:
            orbit.append(w)

    unique = [orbit[0]]
    for w in orbit[1:]:
        is_dup = any(abs(w - u) < 1e-10 for u in unique)
        if not is_dup:
            unique.append(w)
    orbit = unique
    n = len(orbit)

    # The side-pairing translations:
    # For a regular octagon centered at 0, the side-pairing T_k maps
    # edge k to edge k+4. In the Poincare disc, this is a Mobius
    # transformation that translates along the geodesic through the
    # midpoints of edges k and k+4.

    # The midpoint of edge k is at distance R*cos(π/8) from center,
    # at angle kπ/4. The geodesic through m_k and m_{k+4} passes
    # through the center (since they're diametrically opposite).

    # So T_k is a HYPERBOLIC TRANSLATION along the line through 0
    # at angle kπ/4, by distance 2 * R_mid (twice the center-to-midpoint distance).

    R_disc = 0.810465
    mid_r = R_disc * cos(pi / 8)  # Euclidean distance of midpoint from center

    # Hyperbolic distance of midpoint from center:
    mid_hyp = 2 * atanh(mid_r)

    # Translation distance = 2 * mid_hyp (from midpoint to its pair)
    trans_dist = 2 * mid_hyp

    print(f"  Edge midpoint distance: {mid_hyp:.6f} (hyperbolic)")
    print(f"  Translation distance: {trans_dist:.6f}")
    print(f"  Kernel at translation distance: {havelock_kernel(trans_dist):.6f}")

    # The side-pairing T_k translates z along the geodesic at angle kπ/4.
    # In the Poincare disc: translation by distance d along the real axis is:
    #   z -> (z + t)/(1 + conj(t)*z) where t = tanh(d/2)
    # For angle θ: rotate, translate, rotate back.

    t_param = tanh(trans_dist / 2)

    def translate(z, angle, dist):
        """Translate z by hyperbolic distance dist along direction angle."""
        t = tanh(dist / 2)
        # Rotate to real axis, translate, rotate back
        z_rot = z * np.exp(-1j * angle)
        z_trans = (z_rot + t) / (1 + t * np.conj(z_rot))
        return z_trans * np.exp(1j * angle)

    # Generate the 4 independent translations and their inverses (8 total)
    translations = []
    for k in range(4):
        angle = k * pi / 4
        translations.append((angle, trans_dist))
        translations.append((angle, -trans_dist))

    print(f"  Generated {len(translations)} side-pairing translations")

    # Compute the LATTICE-SUMMED interaction matrix
    # For each pair (i, j): add contributions from the 8 nearest Γ-images
    print(f"\n  Computing lattice-summed {n}×{n} matrix...")
    print(f"  (including {len(translations)} nearest images per point)")

    M_lattice = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i == j:
                # Self-energy: sum over non-identity Γ-images
                total = 0.0
                for angle, dist in translations:
                    w_image = translate(orbit[j], angle, dist)
                    d = hyp_dist_disc(orbit[i], w_image)
                    total += havelock_kernel(d)
                M_lattice[i][j] = total
            else:
                # Direct + image contributions
                d_direct = hyp_dist_disc(orbit[i], orbit[j])
                total = havelock_kernel(d_direct)
                for angle, dist in translations:
                    w_image = translate(orbit[j], angle, dist)
                    d = hyp_dist_disc(orbit[i], w_image)
                    total += havelock_kernel(d)
                M_lattice[i][j] = total

    # Eigenvalues
    eigenvalues = np.linalg.eigvalsh(M_lattice)
    eigenvalues = sorted(eigenvalues, reverse=True)

    print(f"\n  Eigenvalues of the lattice-summed {n}×{n} matrix:")
    for i, ev in enumerate(eigenvalues):
        print(f"    λ_{i:2d} = {ev:14.10f}")

    # Degeneracy analysis
    print(f"\n  Degeneracy analysis (tolerance 10^-3):")
    groups = []
    used = set()
    for i in range(n):
        if i in used:
            continue
        group = [i]
        for j in range(i+1, n):
            if j in used:
                continue
            if abs(eigenvalues[i] - eigenvalues[j]) < 1e-3:
                group.append(j)
                used.add(j)
        used.add(i)
        groups.append((eigenvalues[group[0]], len(group)))

    print(f"  {'eigenvalue':>14s} {'mult':>6s} {'type':>20s}")
    for ev, mult in groups:
        if mult == 1:
            rep = "1D"
        elif mult == 2:
            rep = "*** 2D IRREP ***"
        elif mult == 3:
            rep = "3D"
        elif mult == 4:
            rep = "4D (2×2D?)"
        else:
            rep = f"{mult}D"
        print(f"  {ev:14.8f} {mult:6d} {rep:>20s}")

    n_2d = sum(1 for _, m in groups if m == 2)
    if n_2d > 0:
        print(f"\n  *** FOUND {n_2d} TWO-DIMENSIONAL IRREPS ***")
        for ev, m in groups:
            if m == 2:
                print(f"  *** GL(2) eigenvalue candidate: {ev:.10f} ***")


# =====================================================================
# MAIN
# =====================================================================

def main():
    print("=" * 72)
    print("  FULL 48-POINT VORTEX ON THE BOLZA SURFACE")
    print("  (Using D_8 × Z/2 subgroup, 32 elements)")
    print("=" * 72)

    orbit, eigenvalues, groups = orbit_interaction()
    lattice_sum_interaction()


if __name__ == "__main__":
    main()
